version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:11minhan@host.docker.internal:3306/test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/test-db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
